import { useState } from "react";
import { Toaster, sileo } from "sileo";

type Order = { id: string; order_number: string; customer_name: string; customer_phone: string; estimated_total: number; currency: string; order_status: string; procurement_status: string; fulfillment_status: string; payment_status: string; created_at: string };
type Props = { initialOrders: Order[] };
const fields = [{ key: "orderStatus", label: "Pedido", values: ["pending_review", "confirmed", "cancelled", "completed"] }, { key: "procurementStatus", label: "Abastecimiento", values: ["not_required", "pending_supplier", "ordered", "received"] }, { key: "fulfillmentStatus", label: "Entrega", values: ["pending", "ready", "delivered"] }, { key: "paymentStatus", label: "Pago", values: ["pending", "partial", "paid"] }] as const;
const labels: Record<string, string> = { pending_review: "Pendiente de revisión", confirmed: "Confirmado", cancelled: "Cancelado", completed: "Completado", not_required: "No requerido", pending_supplier: "Pendiente de proveedor", ordered: "Solicitado al proveedor", received: "Recibido", pending: "Pendiente", ready: "Listo", delivered: "Entregado", partial: "Anticipo registrado", paid: "Pagado" };

export default function OrderManager({ initialOrders }: Props) {
  const [orders, setOrders] = useState(initialOrders); const [saving, setSaving] = useState<string | null>(null);
  async function save(order: Order) { setSaving(order.id); try { const r = await sileo.promise(fetch("/api/admin/orders", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: order.id, orderStatus: order.order_status, procurementStatus: order.procurement_status, fulfillmentStatus: order.fulfillment_status, paymentStatus: order.payment_status }) }).then(async x => { const d = await x.json() as { order?: Partial<Order>; error?: string }; if (!x.ok) throw new Error(d.error); return d; }), { loading: { title: "Actualizando pedido…" }, success: { title: "Pedido actualizado" }, error: e => ({ title: "No se pudo actualizar", description: String(e) }) }); setOrders(current => current.map(item => item.id === order.id ? { ...item, ...r.order } : item)); } catch {} finally { setSaving(null); } }
  function change(id: string, key: keyof Order, value: string) { setOrders(current => current.map(order => order.id === id ? { ...order, [key]: value } : order)); }
    return <section className="mt-12 border-t border-border-subtle pt-10"><Toaster position="top-right" options={{ fill: "#fff", roundness: 16 }} /><p className="text-xs font-semibold tracking-[.14em] text-brand-primary uppercase">Solicitudes</p><h2 className="mt-2 font-display text-2xl font-semibold">Pedidos recibidos</h2>{orders.length === 0 ? <p className="mt-5 text-sm text-text-secondary">Aún no hay solicitudes.</p> : <ul className="mt-5 grid grid-cols-[repeat(auto-fill,minmax(20rem,20rem))] gap-4">{orders.map(order => <li className="rounded-[20px] border border-border-subtle bg-surface-card p-5" key={order.id}><p className="text-xs font-semibold text-brand-primary">{order.order_number}</p><h3 className="mt-2 font-display text-xl">{order.customer_name}</h3><a className="mt-1 block text-sm text-brand-primary hover:underline" href={`https://wa.me/${order.customer_phone.replace(/\D/g, "")}?text=${encodeURIComponent(`Hola, te contactamos por tu solicitud ${order.order_number} de Alma Esencia CR.`)}`} target="_blank" rel="noreferrer">Contactar por WhatsApp</a><p className="mt-3 text-sm font-semibold">₡{Number(order.estimated_total).toLocaleString("es-CR")} estimado</p><div className="mt-4 grid gap-3">{fields.map(field => <label className="text-xs font-semibold text-text-secondary" key={field.key}>{field.label}<select className="mt-1 min-h-10 w-full rounded-lg border border-border-subtle bg-white px-2 text-sm text-text-primary" value={order[field.key === "orderStatus" ? "order_status" : field.key === "procurementStatus" ? "procurement_status" : field.key === "fulfillmentStatus" ? "fulfillment_status" : "payment_status"]} onChange={e => change(order.id, field.key === "orderStatus" ? "order_status" : field.key === "procurementStatus" ? "procurement_status" : field.key === "fulfillmentStatus" ? "fulfillment_status" : "payment_status", e.target.value)}>{field.values.map(value => <option key={value} value={value}>{labels[value]}</option>)}</select></label>)}</div><button className="mt-5 min-h-11 w-full rounded-full bg-brand-primary text-sm font-semibold text-white disabled:bg-brand-primary-soft" type="button" disabled={saving === order.id} onClick={() => void save(order)}>{saving === order.id ? "Guardando…" : "Guardar estados"}</button></li>)}</ul>}</section>;
}
